Repository helmwave/docs, pull requests merged in 2022-01, with the labels that each got.

#17 Update yaml.md: fix typo
  docs/yaml.md
Labels: size/XS

#18 Add comparison to helmfile and helmsman
  docs/intro.md
  docs/yaml.md
  mkdocs.yml
Labels: size/L

#19 0.16.x
  README.md
  docs/ci.md
  docs/cli.md
  docs/examples/apps-per-ns/README.md
  docs/examples/apps-per-ns/helmwave.yml
  docs/examples/apps-per-ns/helmwave.yml.tpl
  docs/examples/apps-per-ns/values/harbor.yml
  docs/examples/apps-per-ns/values/minio.yml
  docs/examples/apps-per-ns/values/plantuml.yml
  docs/examples/apps-per-ns/values/renovate.yml
  docs/examples/apps-per-ns/vars.yaml
  docs/examples/aws-sm/README.md
  docs/examples/aws-sm/helmwave.yml
  docs/examples/aws-sm/vaules-secret.yaml
  docs/examples/index.md
  docs/examples/pass-git-commit/README.md
  docs/examples/pass-git-commit/helmwave.yml
  docs/examples/pass-git-commit/values.yml
  docs/examples/pass-git-tag/README.md
  docs/examples/pass-git-tag/helmwave.yml
  docs/examples/pass-git-tag/values.yml
  docs/examples/private-github-repo/README.md
  docs/examples/private-github-repo/helmwave.yml
  docs/examples/private-github-repo/helmwave.yml.tpl
  docs/examples/quick-start/README.md
  docs/examples/quick-start/helmwave.yml
  docs/examples/single-app-multi-envs/README.md
  docs/examples/single-app-multi-envs/helmwave.yml
  docs/examples/single-app-multi-envs/helmwave.yml.tpl
  docs/examples/single-app-multi-envs/values/_.yml
  docs/examples/single-app-multi-envs/values/prod.yml
  docs/examples/single-app-multi-envs/values/qa.yml
  docs/examples/single-app-multi-envs/values/stage.yml
  docs/install.md
  docs/intro.md
  docs/tpl.md
  docs/yaml.md
  mkdocs.yml
Labels: size/XXL

#20 0.16.x
  mkdocs.yml
Labels: size/S

#21 Update: intro.md
  docs/intro.md
Labels: size/XS

#23 Store
  docs/examples/private-github-repo/README.md
  docs/examples/single-app-multi-envs/README.md
  docs/examples/store-greeting-hello/README.md
  docs/examples/store-greeting-hello/a.yml
  docs/examples/store-greeting-hello/b.yml
  docs/examples/store-greeting-hello/helmwave.yml
  docs/yaml.md
Labels: size/L
