Repository helmwave/docs, pull requests merged in 2022-08, with the labels that each got.

#37 0.21.x
  .github/workflows/generate-new-version.yml
  README.md
  docs/ci.md
  docs/cli.md
  docs/examples/apps-per-ns/README.md
  docs/examples/apps-per-ns/helmwave.yml
  docs/examples/apps-per-ns/helmwave.yml.tpl
  docs/examples/aws-sm/README.md
  docs/examples/built-in-release/README.md
  docs/examples/kubedog/README.md
  docs/examples/kubedog/helmwave.yml
  docs/examples/oci/README.md
  docs/examples/oci/helmwave.yml
  docs/examples/pass-git-commit/README.md
  docs/examples/pass-git-commit/helmwave.yml
  docs/examples/pass-git-tag/README.md
  docs/examples/pass-git-tag/helmwave.yml
  docs/examples/private-github-repo/README.md
  docs/examples/private-github-repo/helmwave.yml
  docs/examples/private-github-repo/helmwave.yml.tpl
  docs/examples/private-gitlab-repo/README.md
  docs/examples/private-gitlab-repo/helmwave.yml.tpl
  docs/examples/quick-start/README.md
  docs/examples/quick-start/helmwave.yml
  docs/examples/single-app-multi-envs/README.md
  docs/examples/single-app-multi-envs/helmwave.yml
  docs/examples/single-app-multi-envs/helmwave.yml.tpl
  docs/examples/store-greeting-hello/README.md
  docs/examples/vault/README.md
  docs/install.md
  docs/pub.md
  docs/tpl.md
  docs/yaml.md
  mkdocs.yml
Labels: size/L

#38 Fix compasion
  docs/intro.md
Labels: size/M

#39 0.21.x
  docs/intro.md
Labels: size/M

#41 Stupid cherry pick
  docs/examples/single-app-multi-envs/values/_.yml
  docs/examples/store-greeting-hello/README.md
  docs/examples/values-render-flag/README.md
  docs/examples/values-render-flag/helmwave.yml
  docs/examples/values-render-flag/values.yml
  docs/examples/values-strict-flag/README.md
  docs/examples/values-strict-flag/helmwave.yml
  docs/examples/vault/README.md
  docs/yaml.md
  mkdocs.yml
Labels: size/L

#44 0.21.x
  .github/workflows/generate-new-version.yml
  docs/examples/hate-umbrella/README.md
  docs/examples/hate-umbrella/helmwave.yml
  mkdocs.yml
Labels: size/M

#45 0.21.x
  .github/workflows/generate-new-version.yml
  .github/workflows/publish-b.yml
  README.md
  docs/ci.md
  docs/examples/apps-per-ns/README.md
  docs/examples/aws-sm/README.md
  docs/examples/aws-sm/helmwave.yml
  docs/examples/aws-sm/values-secret.yaml
  docs/examples/built-in-release/README.md
  docs/examples/kubedog/README.md
  docs/examples/oci-private/README.md
  docs/examples/oci-public/README.md
  docs/examples/pass-git-commit/README.md
  docs/examples/pass-git-tag/README.md
  docs/examples/private-github-repo/README.md
  docs/examples/private-gitlab-repo/README.md
  docs/examples/quick-start/README.md
  docs/examples/single-app-multi-envs/README.md
  docs/examples/store-greeting-hello/README.md
  docs/examples/values-render-flag/README.md
  docs/examples/values-render-flag/helmwave.yml
  docs/examples/values-strict-flag/README.md
  docs/examples/values-strict-flag/helmwave.yml
  docs/examples/vault/README.md
  docs/examples/vault/helmwave.yml
  docs/examples/vault/values-secret.yaml
  docs/pub.md
  docs/yaml.md
  mkdocs.yml
Labels: size/L

#46 0.21.x
  .github/workflows/linter.yml
  README.md
Labels: size/S

#48 nice
  README.md
Labels: size/XS
