Repository helmwave/docs, pull requests merged in 2023-06, with the labels that each got.

#58 0.27.x
  .gitignore
  docs/anno.md
  docs/assets/yaml-schema-idea-bar.png
  docs/assets/yaml-schema-idea-file.png
  docs/assets/yaml-schema-idea.png
  docs/assets/yaml-schema-vscode.png
  docs/ci.md
  docs/cli.md
  docs/examples/apps-per-ns/.gitlab-ci.yml
  docs/examples/apps-per-ns/README.md
  docs/examples/apps-per-ns/helmwave.yml
  docs/examples/apps-per-ns/helmwave.yml.tpl
  docs/examples/built-in-release/README.md
  docs/examples/built-in-release/helmwave.yml
  docs/examples/hate-umbrella/README.md
  docs/examples/hate-umbrella/helmwave.yml
  docs/examples/kubedog/README.md
  docs/examples/kubedog/helmwave.yml
  docs/examples/oci-private/README.md
  docs/examples/oci-private/helmwave.yml
  docs/examples/oci-public/README.md
  docs/examples/oci-public/helmwave.yml
  docs/examples/pass-git-commit/README.md
  docs/examples/pass-git-commit/helmwave.yml
  docs/examples/pass-git-tag/README.md
  docs/examples/pass-git-tag/helmwave.yml
  docs/examples/private-github-repo/README.md
  docs/examples/private-github-repo/helmwave.yml
  docs/examples/private-github-repo/helmwave.yml.tpl
  docs/examples/private-gitlab-repo/README.md
  docs/examples/private-gitlab-repo/helmwave.yml.tpl
  docs/examples/quick-start/README.md
  docs/examples/quick-start/helmwave.yml
  docs/examples/single-app-multi-envs/README.md
  docs/examples/single-app-multi-envs/helmwave.yml
  docs/examples/single-app-multi-envs/helmwave.yml.tpl
  docs/examples/store-greeting-hello/README.md
  docs/examples/values-delimiter-flags/README.md
  docs/examples/values-delimiter-flags/helmwave.yml
  docs/examples/values-render-flag/helmwave.yml
  docs/examples/values-strict-flag/helmwave.yml
  docs/examples/vault/README.md
  docs/examples/vault/helmwave.yml
  docs/ide.md
  docs/install.md
  docs/intro.md
  docs/overrides/main.html
  docs/tpl.md
  docs/yaml.md
  mkdocs.yml
Labels: size/XL

#59 0.27.x
  README.md
  docs/anno.md
  docs/ci.md
  docs/cli.md
  docs/examples/hate-umbrella/README.md
  docs/examples/kubedog/README.md
  docs/examples/private-env/README.md
  docs/examples/private-env/helmwave.yml
  docs/examples/private-gitlab-repo/README.md
  docs/examples/quick-start/README.md
  docs/examples/values-delimiter-flags/README.md
  docs/intro.md
  docs/overrides/main.html
  docs/tpl.md
  docs/yaml.md
  mkdocs.yml
Labels: size/XL

#62 0.28.x
  docs/assets/kubedog.png
  docs/ci.md
  docs/cli.md
  docs/examples/aws-sm/README.md
  docs/examples/built-in-release/README.md
  docs/examples/graph/README.md
  docs/examples/graph/helmwave.yml
  docs/examples/kubedog/README.md
  docs/examples/lifecycle/README.md
  docs/examples/lifecycle/helmwave.yml
  docs/examples/oci-private/README.md
  docs/examples/oci-public/README.md
  docs/examples/pass-git-commit/README.md
  docs/examples/pass-git-tag/README.md
  docs/examples/private-env/README.md
  docs/examples/private-github-repo/README.md
  docs/examples/private-gitlab-repo/README.md
  docs/examples/store-greeting-hello/README.md
  docs/examples/tags/README.md
  docs/examples/umbrella-evil/README.md
  docs/examples/umbrella-evil/helmwave.yml
  docs/examples/vault/README.md
  docs/flags/graph-width.md
  docs/flags/progress.md
  docs/intro.md
  docs/yaml.md
  mkdocs.yml
Labels: size/L

#63 0.28.x
  .github/workflows/publish-b.yml
  docs/ide.md
  docs/tpl.md
  docs/yaml.md
Labels: size/M

#65 Update docs for 0.29.2
  .github/workflows/publish-b.yml
  docs/examples/full/helmwave.yml
  docs/yaml.md
  mkdocs.yml
Labels: size/S
